import chalk from 'chalk';
import Table from 'cli-table3';
import {
  loadFilterConfig,
  loadOutputStats,
  autoGenerateRules,
} from '@claudeview/core';
import { formatTokens } from '../formatters.js';

export async function filtersCommand(options: { readonly autoUpdate?: boolean }): Promise<void> {
  if (options.autoUpdate) {
    const newRules = await autoGenerateRules();
    if (newRules.length > 0) {
      console.log(chalk.green(`  ${newRules.length} new filter rule(s) auto-generated:\n`));
      for (const rule of newRules) {
        console.log(`  + ${rule.description}`);
      }
      console.log();
    } else {
      console.log(chalk.dim('  No new rules to generate (need more data).\n'));
    }
  }

  const config = await loadFilterConfig();

  console.log(chalk.bold('  Filter Rules'));
  console.log(chalk.dim(`  ${'─'.repeat(50)}`));
  console.log(`  Status: ${config.enabled ? chalk.green('ENABLED') : chalk.red('DISABLED')}`);
  console.log(`  Global max lines: ${config.globalMaxLines}`);
  console.log();

  const table = new Table({
    head: [
      chalk.cyan('Pattern'),
      chalk.cyan('Max Lines'),
      chalk.cyan('Hits'),
      chalk.cyan('Tokens Saved'),
      chalk.cyan('Auto'),
      chalk.cyan('Enabled'),
    ],
  });

  for (const rule of config.rules) {
    table.push([
      rule.pattern.length > 35 ? rule.pattern.slice(0, 32) + '...' : rule.pattern,
      String(rule.maxLines),
      String(rule.hitCount),
      formatTokens(rule.totalTokensSaved),
      rule.autoGenerated ? chalk.yellow('yes') : chalk.dim('no'),
      rule.enabled ? chalk.green('yes') : chalk.red('no'),
    ]);
  }

  console.log(table.toString());

  // Show output stats if available
  const stats = await loadOutputStats();
  if (stats.length > 0) {
    console.log();
    console.log(chalk.bold('  Heavy Output Commands (tracked)'));
    console.log(chalk.dim(`  ${'─'.repeat(50)}`));

    const heavyStats = stats
      .filter((s) => s.estimatedTokens > 500)
      .slice(0, 10);

    if (heavyStats.length > 0) {
      const statsTable = new Table({
        head: [
          chalk.cyan('Command'),
          chalk.cyan('Max Lines'),
          chalk.cyan('Est. Tokens'),
          chalk.cyan('Seen'),
        ],
      });

      for (const stat of heavyStats) {
        statsTable.push([
          stat.normalizedCommand.length > 40
            ? stat.normalizedCommand.slice(0, 37) + '...'
            : stat.normalizedCommand,
          String(stat.outputLines),
          formatTokens(stat.estimatedTokens),
          `${stat.count}x`,
        ]);
      }

      console.log(statsTable.toString());
    } else {
      console.log(chalk.dim('  No heavy commands tracked yet.'));
    }
  }
}
