import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { homedir } from 'node:os';

const CLAUDEVIEW_DIR = join(homedir(), '.claudeview');
const FILTERS_PATH = join(CLAUDEVIEW_DIR, 'filters.json');
const STATS_PATH = join(CLAUDEVIEW_DIR, 'output-stats.json');

export interface FilterRule {
  readonly pattern: string;
  readonly maxLines: number;
  readonly tailLines?: number;
  readonly description: string;
  readonly enabled: boolean;
  readonly autoGenerated: boolean;
  readonly hitCount: number;
  readonly totalTokensSaved: number;
}

export interface OutputStat {
  readonly command: string;
  readonly normalizedCommand: string;
  readonly outputLines: number;
  readonly outputChars: number;
  readonly estimatedTokens: number;
  readonly timestamp: string;
  readonly count: number;
}

export interface FilterConfig {
  readonly rules: readonly FilterRule[];
  readonly globalMaxLines: number;
  readonly enabled: boolean;
}

const DEFAULT_RULES: readonly FilterRule[] = [
  {
    pattern: '^npm install',
    maxLines: 15,
    description: 'npm install: keep only summary and errors',
    enabled: true,
    autoGenerated: false,
    hitCount: 0,
    totalTokensSaved: 0,
  },
  {
    pattern: '^npm (run )?build',
    maxLines: 30,
    description: 'Build output: truncate verbose compilation logs',
    enabled: true,
    autoGenerated: false,
    hitCount: 0,
    totalTokensSaved: 0,
  },
  {
    pattern: '^(npx )?(vitest|jest|mocha)',
    maxLines: 50,
    description: 'Test output: keep failures and summary',
    enabled: true,
    autoGenerated: false,
    hitCount: 0,
    totalTokensSaved: 0,
  },
  {
    pattern: '^git log(?! .*(--oneline|-1|head))',
    maxLines: 40,
    description: 'git log without --oneline: truncate long history',
    enabled: true,
    autoGenerated: false,
    hitCount: 0,
    totalTokensSaved: 0,
  },
  {
    pattern: '^(pip|pip3) install',
    maxLines: 10,
    description: 'pip install: keep only result',
    enabled: true,
    autoGenerated: false,
    hitCount: 0,
    totalTokensSaved: 0,
  },
  {
    pattern: '^cargo build',
    maxLines: 30,
    description: 'Cargo build: truncate verbose output',
    enabled: true,
    autoGenerated: false,
    hitCount: 0,
    totalTokensSaved: 0,
  },
  {
    pattern: '^(npx )?(tsc|typescript)',
    maxLines: 40,
    description: 'TypeScript: keep errors, truncate noise',
    enabled: true,
    autoGenerated: false,
    hitCount: 0,
    totalTokensSaved: 0,
  },
  {
    pattern: '^docker (build|compose)',
    maxLines: 30,
    description: 'Docker: truncate layer-by-layer output',
    enabled: true,
    autoGenerated: false,
    hitCount: 0,
    totalTokensSaved: 0,
  },
];

const DEFAULT_CONFIG: FilterConfig = {
  rules: DEFAULT_RULES,
  globalMaxLines: 200,
  enabled: true,
};

async function ensureDir(): Promise<void> {
  await mkdir(CLAUDEVIEW_DIR, { recursive: true });
}

export async function loadFilterConfig(): Promise<FilterConfig> {
  try {
    const content = await readFile(FILTERS_PATH, 'utf-8');
    return JSON.parse(content) as FilterConfig;
  } catch {
    await saveFilterConfig(DEFAULT_CONFIG);
    return DEFAULT_CONFIG;
  }
}

export async function saveFilterConfig(config: FilterConfig): Promise<void> {
  await ensureDir();
  await writeFile(FILTERS_PATH, JSON.stringify(config, null, 2), 'utf-8');
}

export async function loadOutputStats(): Promise<readonly OutputStat[]> {
  try {
    const content = await readFile(STATS_PATH, 'utf-8');
    return JSON.parse(content) as OutputStat[];
  } catch {
    return [];
  }
}

async function saveOutputStats(stats: readonly OutputStat[]): Promise<void> {
  await ensureDir();
  await writeFile(STATS_PATH, JSON.stringify(stats, null, 2), 'utf-8');
}

function normalizeCommand(command: string): string {
  return command
    .replace(/\/[^\s]+\//g, '/.../')  // strip absolute paths
    .replace(/"[^"]*"/g, '"..."')      // strip quoted strings
    .replace(/\s+/g, ' ')             // normalize whitespace
    .trim()
    .split(' ')
    .slice(0, 3)                       // keep first 3 tokens
    .join(' ');
}

export function findMatchingRule(command: string, config: FilterConfig): FilterRule | null {
  if (!config.enabled) return null;

  for (const rule of config.rules) {
    if (!rule.enabled) continue;
    try {
      const regex = new RegExp(rule.pattern, 'i');
      if (regex.test(command.trim())) {
        return rule;
      }
    } catch {
      continue;
    }
  }
  return null;
}

export function applyFilter(output: string, rule: FilterRule | null, globalMaxLines: number): {
  readonly filtered: string;
  readonly originalLines: number;
  readonly keptLines: number;
  readonly truncated: boolean;
} {
  const lines = output.split('\n');
  const originalLines = lines.length;
  const maxLines = rule?.maxLines ?? globalMaxLines;

  if (originalLines <= maxLines) {
    return { filtered: output, originalLines, keptLines: originalLines, truncated: false };
  }

  const tailCount = rule?.tailLines ?? Math.min(5, Math.floor(maxLines * 0.2));
  const headCount = maxLines - tailCount - 1; // -1 for the truncation message

  const head = lines.slice(0, headCount);
  const tail = lines.slice(-tailCount);
  const skipped = originalLines - headCount - tailCount;

  const truncationMsg = `\n... [claudeview: ${skipped} lines truncated, ${originalLines} total] ...\n`;

  const filtered = [...head, truncationMsg, ...tail].join('\n');

  return {
    filtered,
    originalLines,
    keptLines: headCount + tailCount,
    truncated: true,
  };
}

export async function recordOutput(command: string, outputChars: number, outputLines: number): Promise<void> {
  const stats = [...(await loadOutputStats())];
  const normalized = normalizeCommand(command);
  const estimatedTokens = Math.ceil(outputChars / 4);

  const existingIdx = stats.findIndex((s) => s.normalizedCommand === normalized);
  if (existingIdx >= 0) {
    const existing = stats[existingIdx];
    stats[existingIdx] = {
      ...existing,
      outputLines: Math.max(existing.outputLines, outputLines),
      outputChars: Math.max(existing.outputChars, outputChars),
      estimatedTokens: Math.max(existing.estimatedTokens, estimatedTokens),
      timestamp: new Date().toISOString(),
      count: existing.count + 1,
    };
  } else {
    stats.push({
      command: command.slice(0, 200),
      normalizedCommand: normalized,
      outputLines,
      outputChars,
      estimatedTokens,
      timestamp: new Date().toISOString(),
      count: 1,
    });
  }

  // Keep only top 100 by count
  stats.sort((a, b) => b.count - a.count);
  await saveOutputStats(stats.slice(0, 100));
}

export async function autoGenerateRules(): Promise<readonly FilterRule[]> {
  const stats = await loadOutputStats();
  const config = await loadFilterConfig();
  const newRules: FilterRule[] = [];

  for (const stat of stats) {
    // If a command consistently produces >200 lines and is run often
    if (stat.count >= 3 && stat.outputLines > 200) {
      const alreadyHasRule = config.rules.some((r) => {
        try {
          return new RegExp(r.pattern, 'i').test(stat.command);
        } catch {
          return false;
        }
      });

      if (!alreadyHasRule) {
        const escaped = stat.normalizedCommand.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        newRules.push({
          pattern: `^${escaped}`,
          maxLines: Math.min(50, Math.ceil(stat.outputLines * 0.2)),
          description: `Auto: "${stat.normalizedCommand}" averages ${stat.outputLines} lines (seen ${stat.count}x)`,
          enabled: true,
          autoGenerated: true,
          hitCount: 0,
          totalTokensSaved: 0,
        });
      }
    }
  }

  if (newRules.length > 0) {
    const updatedConfig: FilterConfig = {
      ...config,
      rules: [...config.rules, ...newRules],
    };
    await saveFilterConfig(updatedConfig);
  }

  return newRules;
}

export async function updateRuleStats(pattern: string, tokensSaved: number): Promise<void> {
  const config = await loadFilterConfig();
  const updatedRules = config.rules.map((rule) =>
    rule.pattern === pattern
      ? { ...rule, hitCount: rule.hitCount + 1, totalTokensSaved: rule.totalTokensSaved + tokensSaved }
      : rule
  );
  await saveFilterConfig({ ...config, rules: updatedRules });
}
