import type {
  SessionSummary,
  SessionAnalysis,
  TokenBreakdown,
  TokenTrend,
  TokenHog,
} from './types.js';

// Pricing per 1M tokens (Claude Sonnet 4, approximate)
const INPUT_PRICE_PER_1M = 3.0;
const OUTPUT_PRICE_PER_1M = 15.0;
const CACHE_WRITE_PRICE_PER_1M = 3.75;
const CACHE_READ_PRICE_PER_1M = 0.30;

// Rough estimate: 1 token ≈ 4 characters
const CHARS_PER_TOKEN = 4;

function estimateTokens(charCount: number): number {
  return Math.ceil(charCount / CHARS_PER_TOKEN);
}

function calculateCost(session: SessionSummary): number {
  const inputCost = (session.totalInputTokens / 1_000_000) * INPUT_PRICE_PER_1M;
  const outputCost = (session.totalOutputTokens / 1_000_000) * OUTPUT_PRICE_PER_1M;
  const cacheWriteCost = (session.totalCacheCreationTokens / 1_000_000) * CACHE_WRITE_PRICE_PER_1M;
  const cacheReadCost = (session.totalCacheReadTokens / 1_000_000) * CACHE_READ_PRICE_PER_1M;
  return inputCost + outputCost + cacheWriteCost + cacheReadCost;
}

function computeBreakdown(session: SessionSummary): readonly TokenBreakdown[] {
  const grandTotal = session.totalInputTokens + session.totalOutputTokens
    + session.totalCacheCreationTokens + session.totalCacheReadTokens;
  if (grandTotal === 0) return [];

  const categories: TokenBreakdown[] = [];

  // Input vs Output split
  categories.push({
    category: 'Input Tokens',
    tokens: session.totalInputTokens,
    percentage: (session.totalInputTokens / grandTotal) * 100,
    details: 'Tokens sent to Claude (system prompt, conversation, tool results)',
  });

  categories.push({
    category: 'Output Tokens',
    tokens: session.totalOutputTokens,
    percentage: (session.totalOutputTokens / grandTotal) * 100,
    details: 'Tokens generated by Claude (responses, tool calls)',
  });

  if (session.totalCacheCreationTokens > 0) {
    categories.push({
      category: 'Cache Write',
      tokens: session.totalCacheCreationTokens,
      percentage: (session.totalCacheCreationTokens / grandTotal) * 100,
      details: 'Tokens written to prompt cache',
    });
  }

  if (session.totalCacheReadTokens > 0) {
    categories.push({
      category: 'Cache Read',
      tokens: session.totalCacheReadTokens,
      percentage: (session.totalCacheReadTokens / grandTotal) * 100,
      details: 'Tokens read from prompt cache (cheaper)',
    });
  }

  // Estimate content-based breakdown from messages
  let userContentTokens = 0;
  let assistantContentTokens = 0;
  let toolResultTokens = 0;

  for (const msg of session.messages) {
    const estimated = estimateTokens(msg.contentLength);
    if (msg.type === 'tool_result' || msg.toolCalls.length > 0) {
      toolResultTokens += estimated;
    } else if (msg.role === 'user') {
      userContentTokens += estimated;
    } else if (msg.role === 'assistant') {
      assistantContentTokens += estimated;
    }
  }

  const contentTotal = userContentTokens + assistantContentTokens + toolResultTokens;
  if (contentTotal > 0) {
    categories.push({
      category: 'User Messages (est.)',
      tokens: userContentTokens,
      percentage: (userContentTokens / grandTotal) * 100,
      details: 'Estimated tokens from user prompts',
    });

    categories.push({
      category: 'Tool Results (est.)',
      tokens: toolResultTokens,
      percentage: (toolResultTokens / grandTotal) * 100,
      details: 'Estimated tokens from tool call results',
    });
  }

  return categories;
}

function computeTrends(session: SessionSummary): readonly TokenTrend[] {
  const trends: TokenTrend[] = [];
  let cumulativeInput = 0;
  let cumulativeOutput = 0;

  for (let i = 0; i < session.messages.length; i++) {
    const msg = session.messages[i];
    if (msg.usage) {
      cumulativeInput += msg.usage.input_tokens;
      cumulativeOutput += msg.usage.output_tokens;
    }

    if (msg.usage) {
      trends.push({
        messageIndex: i,
        cumulativeInputTokens: cumulativeInput,
        cumulativeOutputTokens: cumulativeOutput,
        role: msg.role,
      });
    }
  }

  return trends;
}

function findTokenHogs(session: SessionSummary): readonly TokenHog[] {
  const toolTokens: Record<string, { tokens: number; count: number }> = {};

  for (const msg of session.messages) {
    for (const tc of msg.toolCalls) {
      const entry = toolTokens[tc.name] ?? { tokens: 0, count: 0 };
      entry.tokens += estimateTokens(msg.contentLength);
      entry.count += 1;
      toolTokens[tc.name] = entry;
    }
  }

  const hogs: TokenHog[] = [];

  for (const [name, data] of Object.entries(toolTokens)) {
    hogs.push({
      name,
      type: 'tool',
      estimatedTokens: data.tokens,
      occurrences: data.count,
    });
  }

  // Sort by estimated tokens descending
  hogs.sort((a, b) => b.estimatedTokens - a.estimatedTokens);

  return hogs.slice(0, 10);
}

export function analyzeSession(session: SessionSummary): SessionAnalysis {
  return {
    sessionId: session.sessionId,
    breakdown: computeBreakdown(session),
    trends: computeTrends(session),
    tokenHogs: findTokenHogs(session),
    totalTokens: session.totalInputTokens + session.totalOutputTokens,
    estimatedCostUsd: calculateCost(session),
  };
}

export function analyzeSessions(sessions: readonly SessionSummary[]): readonly SessionAnalysis[] {
  return sessions.map(analyzeSession);
}

export { calculateCost, estimateTokens };
